### ISSUE TITLE
Add a new feature for noting in code

### ISSUE THREAD

**Issue by hobliu** [Aleeeeexxxxx/marker#27]

**Comment by hobliu** [comment]
@Aleeeeexxxxx   how about adding this feature to support adding notes with some outside-of-source methods, instead of inside-of-source comments.

**Comment by Aleeeeexxxxx** [comment]
![image](https://github.com/user-attachments/assets/482d15f1-4068-4305-955b-d2c51f72dc98)
The feature would be something like this.
